name: dokus-site
recipe: wordpress
config:
  php: '8.1'
  via: nginx
  database: mysql
  webroot: wp
  xdebug: true
  config:
    php: .lando/php.wsl.ini
services:
  appserver:
    overrides:
      environment:
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "client_host=host.docker.internal"
  redis:
    type: redis
    portforward: true
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  proxy:
    appserver:
      - dokus-site.lndo.site